export * from './MainPage';
export * from './AboutPage';
export * from './NotFoundPage';
export * from './LoginPage';
export * from './RegistrationPage';
export * from './ProfilePage';
export * from './ProductPage';
export * from './CategoryPage';
export * from './BasketPage';
